### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Aroksak** [BSData/fallout-wasteland-warfare#9]
Hi! This repo hasn't been updated for long. I've updated all files to match the current rules and made a pull request, and I will be glad to keep maintaining it.

**Comment by amis92** [comment]
Hello, @Aroksak. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Also, join the data author community over at discord!

[![Chat on Discord](https://img.shields.io/discord/558412685981777922.svg?logo=discord&style=popout-square)](https://discord.gg/KqPVhds)

Cheers!

[invitation]: https://github.com/BSData/fallout-wasteland-warfare/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
